# Generated by Django 3.2.4 on 2021-06-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0002_alter_solicitud_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='imagenes'),
        ),
    ]
