# Generated by Django 3.2.4 on 2021-06-23 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0003_alter_solicitud_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
