# Generated by Django 3.2.4 on 2021-07-03 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0005_solicitud_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='es_beneficiario',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='es_diseñador',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='es_ejecutivo_ventas',
            field=models.BooleanField(default=False),
        ),
    ]
