# Generated by Django 3.2.4 on 2021-07-04 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0006_auto_20210703_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='solicitud_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beneficiario.solicitud'),
        ),
    ]
