# Generated by Django 3.2.4 on 2021-07-04 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0007_usuario_solicitud_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='solicitud_id',
        ),
    ]
