# Generated by Django 3.2.4 on 2021-07-04 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0008_remove_usuario_solicitud_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
