# Generated by Django 3.2.4 on 2021-07-04 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0009_solicitud_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='beneficiario.usuario'),
        ),
    ]
