# Generated by Django 3.2.4 on 2021-07-04 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0011_alter_solicitud_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='region',
            field=models.IntegerField(choices=[(1, 'Región de Arica y Parinacota'), (2, 'Región de Tarapacá'), (3, 'Región de Antofagasta'), (4, 'Region de Atacama'), (5, 'Región de Coquimbo'), (6, 'Región de Valparaíso'), (7, 'Región del Libertador General Bernardo OHiggins'), (8, 'Región del Maule'), (9, 'Región del Bio-Bio'), (10, 'Región de la Araucania'), (11, 'Región de los Ríos'), (12, 'Región de los Lagos'), (13, 'Región Aysén del General Carlos Ibáñez del Campo'), (14, 'Región de Magallanes y de la Antártica Chilena'), (15, 'Región Metropolitana de Santiago')], default=1),
        ),
    ]
