# Generated by Django 3.2.4 on 2021-07-04 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0012_solicitud_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='es_diseñador',
        ),
    ]
