# Generated by Django 3.2.4 on 2021-07-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0013_remove_usuario_es_diseñador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='es_beneficiario',
            field=models.BooleanField(default=True),
        ),
    ]
