# Generated by Django 3.2.4 on 2021-07-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0014_alter_usuario_es_beneficiario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cant_solicitud',
            field=models.BooleanField(default=False),
        ),
    ]
